// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2NuuMvow6UokNjIi2F8e7Jx-uOAdCTHA',
    appId: '1:551496281987:web:76ba5dfb0eb32b07f090b6',
    messagingSenderId: '551496281987',
    projectId: 'trainingsplaner-a1c86',
    authDomain: 'trainingsplaner-a1c86.firebaseapp.com',
    storageBucket: 'trainingsplaner-a1c86.appspot.com',
    measurementId: 'G-477440RBHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpHoQSjyhwlaiVsf2tPiFRw0AHHbH_jCg',
    appId: '1:551496281987:android:01e72f8997c23b38f090b6',
    messagingSenderId: '551496281987',
    projectId: 'trainingsplaner-a1c86',
    storageBucket: 'trainingsplaner-a1c86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSRK4T7kLv92jXWAw0NiQiPkSS8iTtmHg',
    appId: '1:551496281987:ios:43b29f5e6f5d27dcf090b6',
    messagingSenderId: '551496281987',
    projectId: 'trainingsplaner-a1c86',
    storageBucket: 'trainingsplaner-a1c86.appspot.com',
    iosBundleId: 'com.example.trainingplaner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSRK4T7kLv92jXWAw0NiQiPkSS8iTtmHg',
    appId: '1:551496281987:ios:43b29f5e6f5d27dcf090b6',
    messagingSenderId: '551496281987',
    projectId: 'trainingsplaner-a1c86',
    storageBucket: 'trainingsplaner-a1c86.appspot.com',
    iosBundleId: 'com.example.trainingplaner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2NuuMvow6UokNjIi2F8e7Jx-uOAdCTHA',
    appId: '1:551496281987:web:be82131eb7125b90f090b6',
    messagingSenderId: '551496281987',
    projectId: 'trainingsplaner-a1c86',
    authDomain: 'trainingsplaner-a1c86.firebaseapp.com',
    storageBucket: 'trainingsplaner-a1c86.appspot.com',
    measurementId: 'G-PBZ2C47LFT',
  );
}
